"""Strategy execution contracts - Protocol and result dataclasses.

Defines the core StrategyProtocol interface and result dataclasses for
strategy execution. Uses typing.Protocol (structural subtyping) not ABC.

Aligns with StrategyExecutor Protocol in backtesting.candidate.walk_forward
and StrategyDSL models in backtesting.dsl.models.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Protocol, runtime_checkable


@dataclass(frozen=True)
class SignalResult:
    """Represents a single trading signal generated by a strategy.

    Attributes:
        signal_type: Type of signal (e.g., "entry", "exit", "stop").
        direction: Trade direction ("long", "short", "flat").
        confidence: Signal confidence score in [0.0, 1.0].
        timestamp: ISO 8601 timestamp string for the signal.
        metadata: Optional additional signal context.
    """

    signal_type: str
    direction: str
    confidence: float
    timestamp: str
    metadata: dict[str, Any] = field(default_factory=dict)

    def __post_init__(self) -> None:
        if not 0.0 <= self.confidence <= 1.0:
            msg = f"confidence must be in [0.0, 1.0], got {self.confidence}"
            raise ValueError(msg)
        if self.signal_type not in ("entry", "exit", "stop", "adjust"):
            msg = f"signal_type must be entry|exit|stop|adjust, got {self.signal_type}"
            raise ValueError(msg)
        if self.direction not in ("long", "short", "flat"):
            msg = f"direction must be long|short|flat, got {self.direction}"
            raise ValueError(msg)


@dataclass(frozen=True)
class ExecutionResult:
    """Result of a strategy execution run.

    Captures P&L, risk metrics, and trade statistics from running
    a strategy against market data.

    Attributes:
        trades: Number of trades executed.
        pnl: Total profit and loss.
        sharpe: Annualized Sharpe ratio.
        max_drawdown: Maximum drawdown as a fraction (e.g., 0.15 = 15%).
        win_rate: Fraction of profitable trades in [0.0, 1.0].
        metadata: Optional additional execution context.
    """

    trades: int
    pnl: float
    sharpe: float
    max_drawdown: float
    win_rate: float
    metadata: dict[str, Any] = field(default_factory=dict)

    def __post_init__(self) -> None:
        if self.trades < 0:
            msg = f"trades must be >= 0, got {self.trades}"
            raise ValueError(msg)
        if not 0.0 <= self.max_drawdown <= 1.0:
            msg = f"max_drawdown must be in [0.0, 1.0], got {self.max_drawdown}"
            raise ValueError(msg)
        if not 0.0 <= self.win_rate <= 1.0:
            msg = f"win_rate must be in [0.0, 1.0], got {self.win_rate}"
            raise ValueError(msg)


@dataclass(frozen=True)
class StrategyMetadata:
    """Metadata describing a strategy implementation.

    Attributes:
        name: Human-readable strategy name.
        version: Semantic version string (e.g., "1.0.0").
        description: Brief strategy description.
        required_signals: List of signal types the strategy requires.
        risk_parameters: Risk-related parameter names and defaults.
    """

    name: str
    version: str
    description: str = ""
    required_signals: list[str] = field(default_factory=list)
    risk_parameters: dict[str, Any] = field(default_factory=dict)

    def __post_init__(self) -> None:
        if not self.name:
            msg = "name must be non-empty"
            raise ValueError(msg)
        if not self.version:
            msg = "version must be non-empty"
            raise ValueError(msg)


@runtime_checkable
class StrategyProtocol(Protocol):
    """Core strategy execution interface.

    All strategy implementations must satisfy this protocol.
    Uses Protocol (structural subtyping) not ABC (nominal subtyping).

    Aligns with StrategyExecutor in backtesting.candidate.walk_forward
    but provides a more comprehensive interface including signal
    generation, config validation, and metadata access.
    """

    @property
    def name(self) -> str:
        """Strategy name identifier."""
        ...

    @property
    def version(self) -> str:
        """Strategy version string."""
        ...

    def validate_config(self, config: dict[str, Any]) -> bool:
        """Validate a strategy configuration dictionary.

        Args:
            config: Strategy configuration to validate.

        Returns:
            True if the configuration is valid for this strategy.
        """
        ...

    def generate_signals(
        self,
        market_data: list[dict[str, Any]],
        config: dict[str, Any],
    ) -> list[SignalResult]:
        """Generate trading signals from market data.

        Args:
            market_data: OHLCV or other market data candles.
            config: Strategy configuration parameters.

        Returns:
            List of trading signals.
        """
        ...

    def execute(
        self,
        strategy_config: dict[str, Any],
        data: list[dict[str, Any]],
        initial_capital: float,
    ) -> dict[str, Any]:
        """Execute strategy on data and return results.

        Compatible with StrategyExecutor Protocol in walk_forward.py.

        Args:
            strategy_config: Strategy configuration dictionary.
            data: OHLCV data to execute against.
            initial_capital: Starting capital for execution.

        Returns:
            Execution results dictionary with keys matching
            ExecutionResult fields.
        """
        ...
