# Grafana Tempo Configuration
# Generated by Terraform for ${environment} environment

server:
  http_listen_port: 3200
  log_level: ${log_level}

distributor:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317
        http:
          endpoint: 0.0.0.0:4318

ingester:
  max_block_duration: 5m
  max_block_bytes: 1000000000  # 1GB
  trace_idle_period: 10s
  flush_check_period: 10s

compactor:
  compaction:
    block_retention: ${retention_hours}h
    compacted_block_retention: 1h

storage:
  trace:
    backend: local
    local:
      path: /tmp/tempo/traces
    wal:
      path: /tmp/tempo/wal
    pool:
      max_workers: 50
      queue_depth: 200

overrides:
  defaults:
    global:
      ingestion_rate_limit_bytes: 20000000  # 20MB/s
      ingestion_burst_size_bytes: 20000000
      max_traces_per_user: 100000
      max_bytes_per_trace: 5000000  # 5MB per trace
      max_search_bytes_per_trace: 0

querier:
  frontend_worker:
    frontend_address: localhost:9095
  max_concurrent_queries: 20

query_frontend:
  max_outstanding_per_tenant: 200
  querier_forget_delay: 0s
  max_retries: 5
  search:
    concurrent_jobs: 1000
    target_bytes_per_job: 104857600  # 100MB
  trace_by_id:
    query_shards: 50
