"""
Signal models for zone-to-signal mapping.

Defines the signal types and data structures produced by the zone-to-signal mapper.
"""

from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from typing import Any
from uuid import UUID, uuid4


class ZoneSignalType(str, Enum):
    """Types of signals generated by zone-to-signal mapping.

    These map to the source zone types:
        - ENTRY: Generated from Order Block zones
        - CONTINUATION: Generated from FVG zones
        - MOMENTUM: Generated from CVD divergence zones
    """

    ENTRY = "entry"  # Entry signals from Order Blocks
    CONTINUATION = "continuation"  # Continuation signals from FVGs
    MOMENTUM = "momentum"  # Momentum signals from CVD divergence


class SignalDirection(str, Enum):
    """Direction of the trading signal."""

    LONG = "long"  # Bullish signal
    SHORT = "short"  # Bearish signal
    NEUTRAL = "neutral"  # No directional bias


class SignalResolution(str, Enum):
    """Resolution status of a zone-to-signal mapping request."""

    SUCCESS = "success"  # Signals generated successfully
    NO_ACTIVE_ZONES = "no_active_zones"  # No active zones found
    ZONES_INVALIDATED = "zones_invalidated"  # All zones are invalidated
    RESOLUTION_ERROR = "resolution_error"  # Error during resolution


@dataclass
class BaseZoneSignal:
    """Base class for zone-generated signals.

    Attributes:
        signal_id: Unique identifier for this signal
        signal_type: Type of signal (ENTRY, CONTINUATION, MOMENTUM)
        direction: Direction of the signal (LONG, SHORT, NEUTRAL)
        zone_uuid: UUID of the source zone
        zone_type: Type of the source zone
        token: Trading pair symbol
        timeframe: Trading timeframe
        price_high: Upper price boundary of the signal
        price_low: Lower price boundary of the signal
        confidence: Confidence score (0.0-1.0)
        zone_status: Status of the zone at signal generation time
        timestamp: When the signal was generated
        metadata: Additional metadata about the signal
    """

    signal_id: UUID = field(default_factory=uuid4)
    signal_type: ZoneSignalType = ZoneSignalType.ENTRY
    direction: SignalDirection = SignalDirection.NEUTRAL
    zone_uuid: UUID = field(default_factory=uuid4)
    zone_type: str = "UNKNOWN"
    token: str = "UNKNOWN"
    timeframe: str = "1H"
    price_high: float = 0.0
    price_low: float = 0.0
    confidence: float = 0.5
    zone_status: str = "ACTIVE"
    timestamp: datetime = field(default_factory=datetime.utcnow)
    metadata: dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> dict[str, Any]:
        """Convert signal to dictionary for serialization."""
        return {
            "signal_id": str(self.signal_id),
            "signal_type": self.signal_type.value,
            "direction": self.direction.value,
            "zone_uuid": str(self.zone_uuid),
            "zone_type": self.zone_type,
            "token": self.token,
            "timeframe": self.timeframe,
            "price_high": round(self.price_high, 2),
            "price_low": round(self.price_low, 2),
            "confidence": round(self.confidence, 4),
            "zone_status": self.zone_status,
            "timestamp": self.timestamp.isoformat(),
            "metadata": self.metadata,
        }


@dataclass
class EntrySignal(BaseZoneSignal):
    """Entry signal generated from an Order Block zone.

    Entry signals indicate potential entry points based on Order Block zones.
    Bullish OB (polarity=bullish) → LONG signal
    Bearish OB (polarity=bearish) → SHORT signal
    """

    signal_type: ZoneSignalType = ZoneSignalType.ENTRY
    entry_type: str = "market"  # "market", "limit", "stop"
    zone_polarity: str = "unknown"  # "bullish" or "bearish" from the OB
    optimal_entry_price: float = 0.0  # Suggested entry price within the zone
    stop_loss: float = 0.0  # Suggested stop loss
    risk_reward_ratio: float = 0.0  # Calculated R:R if applicable

    def to_dict(self) -> dict[str, Any]:
        """Convert entry signal to dictionary."""
        base = super().to_dict()
        base.update(
            {
                "entry_type": self.entry_type,
                "zone_polarity": self.zone_polarity,
                "optimal_entry_price": round(self.optimal_entry_price, 2),
                "stop_loss": round(self.stop_loss, 2),
                "risk_reward_ratio": round(self.risk_reward_ratio, 4),
            }
        )
        return base


@dataclass
class ContinuationSignal(BaseZoneSignal):
    """Continuation signal generated from an FVG zone.

    Continuation signals indicate potential trend continuation based on FVGs.
    Bullish FVG → LONG continuation
    Bearish FVG → SHORT continuation
    """

    signal_type: ZoneSignalType = ZoneSignalType.CONTINUATION
    fvg_direction: str = "unknown"  # "bullish" or "bearish" from the FVG
    mitigation_status: str = "none"  # "none", "wick", "close", "full"
    midpoint: float = 0.0  # Midpoint of the FVG zone
    zone_size: float = 0.0  # Size of the FVG zone

    def to_dict(self) -> dict[str, Any]:
        """Convert continuation signal to dictionary."""
        base = super().to_dict()
        base.update(
            {
                "fvg_direction": self.fvg_direction,
                "mitigation_status": self.mitigation_status,
                "midpoint": round(self.midpoint, 2),
                "zone_size": round(self.zone_size, 4),
            }
        )
        return base


@dataclass
class MomentumSignal(BaseZoneSignal):
    """Momentum signal generated from CVD divergence.

    Momentum signals indicate potential momentum based on CVD divergence.
    Bullish CVD divergence → LONG momentum
    Bearish CVD divergence → SHORT momentum
    """

    signal_type: ZoneSignalType = ZoneSignalType.MOMENTUM
    cvd_direction: str = "unknown"  # "bullish" or "bearish" from CVD
    divergence_strength: float = 0.0  # Strength of the divergence (0.0-1.0)
    threshold: float = 0.0  # Detection threshold used
    price_at_formation: float = 0.0  # Price at which divergence formed

    def to_dict(self) -> dict[str, Any]:
        """Convert momentum signal to dictionary."""
        base = super().to_dict()
        base.update(
            {
                "cvd_direction": self.cvd_direction,
                "divergence_strength": round(self.divergence_strength, 4),
                "threshold": round(self.threshold, 4),
                "price_at_formation": round(self.price_at_formation, 2),
            }
        )
        return base


@dataclass
class ZoneToSignalResult:
    """Result of zone-to-signal mapping operation.

    Contains the generated signals and metadata about the resolution.
    """

    resolution: SignalResolution = SignalResolution.SUCCESS
    entry_signals: list[EntrySignal] = field(default_factory=list)
    continuation_signals: list[ContinuationSignal] = field(default_factory=list)
    momentum_signals: list[MomentumSignal] = field(default_factory=list)
    zones_processed: int = 0
    zones_active: int = 0
    zones_tested: int = 0
    zones_mitigated: int = 0
    zones_invalidated: int = 0
    resolution_time_ms: float = 0.0  # Time taken for resolution in milliseconds
    error_message: str | None = None
    timestamp: datetime = field(default_factory=datetime.utcnow)

    @property
    def total_signals(self) -> int:
        """Total number of signals generated."""
        return (
            len(self.entry_signals)
            + len(self.continuation_signals)
            + len(self.momentum_signals)
        )

    @property
    def all_signals(self) -> list[BaseZoneSignal]:
        """All signals as a single list."""
        return self.entry_signals + self.continuation_signals + self.momentum_signals

    def to_dict(self) -> dict[str, Any]:
        """Convert result to dictionary."""
        return {
            "resolution": self.resolution.value,
            "entry_signals": [s.to_dict() for s in self.entry_signals],
            "continuation_signals": [s.to_dict() for s in self.continuation_signals],
            "momentum_signals": [s.to_dict() for s in self.momentum_signals],
            "total_signals": self.total_signals,
            "zones_processed": self.zones_processed,
            "zones_active": self.zones_active,
            "zones_tested": self.zones_tested,
            "zones_mitigated": self.zones_mitigated,
            "zones_invalidated": self.zones_invalidated,
            "resolution_time_ms": round(self.resolution_time_ms, 3),
            "error_message": self.error_message,
            "timestamp": self.timestamp.isoformat(),
        }
