"""Program Synthesis System for STRONG.

Provides DSL, validation, and safe generation of programs that can be
integrated with the belief system, hypothesis generator, and symbolic rules.
"""

from src.strong_system.program_synthesis.dsl import (
    DSLBuilder,
    ProgramDeserializer,
    ProgramDSL,
    ProgramSerializer,
    SchemaRegistry,
    create_default_schema,
    create_safe_schema,
    create_strategy_schema,
    schema_registry,
)
from src.strong_system.program_synthesis.generator import (
    GenerationConfig,
    GenerationConstraints,
    GenerationContext,
    GenerationStrategy,
    GrammarBasedGenerator,
    HybridGenerator,
    ProgramGenerator,
    SafeGenerator,
    SearchBasedGenerator,
    TemplateBasedGenerator,
    create_generator,
    generate_program,
)
from src.strong_system.program_synthesis.types import (
    ASTNode,
    ASTNodeType,
    BinaryOp,
    BinaryOperator,
    BooleanLiteral,
    CallExpression,
    Conditional,
    FunctionDef,
    NumberLiteral,
    ParameterRef,
    Program,
    ProgramSchema,
    ProgramType,
    Sequence,
    SourceLocation,
    StringLiteral,
    TypeAnnotation,
    UnaryOp,
    UnaryOperator,
    VariableDecl,
    VariableRef,
    VectorLiteral,
)
from src.strong_system.program_synthesis.validator import (
    ProgramValidator,
    SemanticAnalyzer,
    TypeChecker,
    ValidationError,
    ValidationErrorType,
    ValidationResult,
    validate_program,
)

__all__ = [
    # DSL
    "ProgramDSL",
    "DSLBuilder",
    "ProgramSerializer",
    "ProgramDeserializer",
    "SchemaRegistry",
    "schema_registry",
    "create_default_schema",
    "create_safe_schema",
    "create_strategy_schema",
    # Types
    "ASTNode",
    "ASTNodeType",
    "BinaryOp",
    "BinaryOperator",
    "BooleanLiteral",
    "CallExpression",
    "Conditional",
    "FunctionDef",
    "NumberLiteral",
    "ParameterRef",
    "Program",
    "ProgramSchema",
    "ProgramType",
    "Sequence",
    "SourceLocation",
    "StringLiteral",
    "TypeAnnotation",
    "UnaryOp",
    "UnaryOperator",
    "VariableDecl",
    "VariableRef",
    "VectorLiteral",
    # Validator
    "ProgramValidator",
    "TypeChecker",
    "SemanticAnalyzer",
    "ValidationResult",
    "ValidationError",
    "ValidationErrorType",
    "validate_program",
    # Generator
    "ProgramGenerator",
    "TemplateBasedGenerator",
    "SearchBasedGenerator",
    "GrammarBasedGenerator",
    "HybridGenerator",
    "SafeGenerator",
    "GenerationConfig",
    "GenerationConstraints",
    "GenerationContext",
    "GenerationStrategy",
    "create_generator",
    "generate_program",
]
