#!/usr/bin/env python3
"""Ingest skill-autonomy backlog candidates into docs/bmm-workflow-status.yaml.

Design:
- Non-destructive, bounded ingestion from Redis queue.
- Deterministic backlog IDs for dedupe.
- Appends new backlog items before `current_phase:` in the canonical status file.
"""

from __future__ import annotations

import argparse
import contextlib
import json
import os
import re
from dataclasses import dataclass
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

import yaml

try:
    import fcntl
except Exception:  # pragma: no cover
    fcntl = None

QUEUE_KEY_DEFAULT = "bmad:chiseai:skills:backlog:candidates"
STATUS_FILE_DEFAULT = Path("docs/bmm-workflow-status.yaml")


def utc_now() -> datetime:
    return datetime.now(UTC)


def iso(dt: datetime | None = None) -> str:
    return (dt or utc_now()).replace(microsecond=0).isoformat().replace("+00:00", "Z")


def slugify(value: str) -> str:
    s = re.sub(r"[^A-Za-z0-9]+", "-", value.strip())
    s = re.sub(r"-+", "-", s).strip("-")
    return (s or "UNKNOWN").upper()


def priority_rank(p: str) -> int:
    order = {"low": 1, "medium": 2, "high": 3}
    return order.get((p or "").lower(), 1)


def choose_priority(values: list[str]) -> str:
    if not values:
        return "P3"
    best = max(values, key=priority_rank)
    return {"high": "P1", "medium": "P2", "low": "P3"}.get(best.lower(), "P3")


def redis_client():
    try:
        import redis

        port = int(
            os.getenv("REDIS_PORT")
            or os.getenv("CHISE_REDIS_PORT")
            or os.getenv("ACP_REDIS_PORT")
            or "6380"
        )
        db = int(os.getenv("REDIS_DB", "0"))
        hosts = [
            os.getenv("REDIS_HOST"),
            os.getenv("CHISE_REDIS_HOST"),
            os.getenv("ACP_REDIS_HOST"),
            "chiseai-redis",
            "host.docker.internal",
            "localhost",
        ]
        hosts = [h for i, h in enumerate(hosts) if h and h not in hosts[:i]]
        for host in hosts:
            try:
                client = redis.Redis(
                    host=host,
                    port=port,
                    db=db,
                    decode_responses=True,
                    socket_connect_timeout=3,
                    socket_timeout=3,
                )
                client.ping()
                return client
            except Exception:
                continue
        return None
    except Exception:
        return None


@contextlib.contextmanager
def acquire_lock(lock_file: str):
    if not lock_file or fcntl is None:
        yield True
        return

    path = Path(lock_file)
    path.parent.mkdir(parents=True, exist_ok=True)
    fh = path.open("w", encoding="utf-8")
    try:
        fcntl.flock(fh.fileno(), fcntl.LOCK_EX | fcntl.LOCK_NB)
        fh.write(str(datetime.now(UTC).timestamp()))
        fh.flush()
        yield True
    except BlockingIOError:
        yield False
    finally:
        with contextlib.suppress(Exception):
            fcntl.flock(fh.fileno(), fcntl.LOCK_UN)
        fh.close()


@dataclass
class CandidateAggregate:
    backlog_id: str
    title: str
    description: str
    recommended_action: str
    trigger_types: set[str]
    first_seen_week: str
    last_seen_week: str
    occurrences: int
    priority_labels: list[str]

    def to_yaml_block(self, queue_key: str) -> str:
        today = utc_now().date().isoformat()
        priority = choose_priority(self.priority_labels)
        esc_title = self.title.replace("'", "''")
        esc_desc = self.description.replace("'", "''")
        notes = [
            f"Autogenerated from queue: {queue_key}",
            f"Trigger types: {', '.join(sorted(self.trigger_types))}",
            f"Observed occurrences: {self.occurrences}",
            f"Week range: {self.first_seen_week} -> {self.last_seen_week}",
            f"Recommended action: {self.recommended_action}",
        ]

        # Build compact YAML by hand to preserve file style and avoid full-file reformatting.
        lines = [
            f"- created_date: '{today}'",
            f"  id: {self.backlog_id}",
            f"  title: '{esc_title}'",
            f"  description: '{esc_desc}'",
            "  owner: jarvis",
            f"  priority: {priority}",
            "  status: planned",
            "  source: skill_autonomy",
            "  automation:",
            "    generated_by: scripts/ops/ingest_skill_backlog_candidates.py",
            f"    generated_at_utc: '{iso()}'",
            f"    queue_key: {queue_key}",
            f"    first_seen_week: {self.first_seen_week}",
            f"    last_seen_week: {self.last_seen_week}",
            f"    occurrences: {self.occurrences}",
            "  notes:",
        ]
        for note in notes:
            esc = note.replace("'", "''")
            lines.append(f"  - '{esc}'")
        return "\n".join(lines)


def derive_aggregate_id(item: dict[str, Any]) -> tuple[str, str, str, str]:
    if item.get("skill_name"):
        skill = str(item["skill_name"]).strip()
        sid = f"BL-SKILL-AUTO-SKILL-{slugify(skill)}"
        title = f"Add/Import Skill: {skill}"
        desc = f"Repeated missing-skill KPI indicates '{skill}' should be added or imported."
        action = str(
            item.get("recommended_action") or f"Create or import skill '{skill}'."
        )
        return sid, title, desc, action

    task_class = str(item.get("task_class") or "unclassified").strip()
    sid = f"BL-SKILL-AUTO-CLASS-{slugify(task_class)}"
    title = f"Improve Skill Coverage for Task Class: {task_class}"
    desc = (
        "Missing-skill rate for task class "
        f"'{task_class}' crossed threshold and needs skill coverage planning."
    )
    action = str(
        item.get("recommended_action")
        or f"Define/add missing skills for '{task_class}'."
    )
    return sid, title, desc, action


def collect_existing_ids(status_text: str) -> set[str]:
    matches = re.findall(r"(?m)^\s*id:\s*([^\n#]+?)\s*$", status_text)
    return {m.strip() for m in matches}


def insert_backlog_entries(status_text: str, entries: list[str]) -> str:
    marker = "\ncurrent_phase:"
    idx = status_text.find(marker)
    if idx == -1:
        raise RuntimeError("Could not locate 'current_phase:' marker in status file")
    block = "\n" + "\n".join(entries) + "\n"
    return status_text[:idx] + block + status_text[idx:]


def aggregate_candidates(
    raw_items: list[str],
) -> tuple[dict[str, CandidateAggregate], int]:
    aggs: dict[str, CandidateAggregate] = {}
    parse_errors = 0

    for raw in raw_items:
        try:
            item = json.loads(raw)
        except Exception:
            parse_errors += 1
            continue

        backlog_id, title, desc, action = derive_aggregate_id(item)
        week = str(item.get("week_id") or "unknown")
        trig = str(item.get("trigger") or "unknown")
        pri = str(item.get("priority") or "low")

        if backlog_id not in aggs:
            aggs[backlog_id] = CandidateAggregate(
                backlog_id=backlog_id,
                title=title,
                description=desc,
                recommended_action=action,
                trigger_types={trig},
                first_seen_week=week,
                last_seen_week=week,
                occurrences=1,
                priority_labels=[pri],
            )
            continue

        agg = aggs[backlog_id]
        agg.trigger_types.add(trig)
        agg.occurrences += 1
        agg.priority_labels.append(pri)
        if week < agg.first_seen_week:
            agg.first_seen_week = week
        if week > agg.last_seen_week:
            agg.last_seen_week = week

    return aggs, parse_errors


def main() -> int:
    ap = argparse.ArgumentParser(
        description="Ingest skill backlog candidates into workflow status"
    )
    ap.add_argument("--queue-key", default=QUEUE_KEY_DEFAULT)
    ap.add_argument("--status-file", default=str(STATUS_FILE_DEFAULT))
    ap.add_argument("--max-items", type=int, default=100)
    ap.add_argument("--lock-file", default="/tmp/chise-skill-backlog-ingest.lock")
    ap.add_argument("--dry-run", action="store_true")
    args = ap.parse_args()

    status_path = Path(args.status_file)
    if not status_path.exists():
        print(f"ERROR: status file not found: {status_path}")
        return 1

    with acquire_lock(args.lock_file) as lock_ok:
        if not lock_ok:
            print("SKILL_BACKLOG_INGEST_RESULT")
            print(
                yaml.safe_dump(
                    {
                        "generated_at_utc": iso(),
                        "skipped": True,
                        "reason": f"lock busy: {args.lock_file}",
                    },
                    sort_keys=False,
                ).strip()
            )
            return 0

        client = redis_client()
        if client is None:
            print("ERROR: Redis unavailable; cannot ingest queue")
            return 1

        raw_items = client.lrange(args.queue_key, 0, max(args.max_items - 1, 0))
        if not raw_items:
            print("SKILL_BACKLOG_INGEST_RESULT")
            print(
                yaml.safe_dump(
                    {"ingested": 0, "skipped": 0, "queue_items_read": 0},
                    sort_keys=False,
                ).strip()
            )
            return 0

        aggs, parse_errors = aggregate_candidates(raw_items)

        status_text = status_path.read_text(encoding="utf-8")
        existing_ids = collect_existing_ids(status_text)

        new_entries: list[str] = []
        skipped = 0
        for backlog_id, agg in sorted(aggs.items(), key=lambda kv: kv[0]):
            if backlog_id in existing_ids:
                skipped += 1
                continue
            new_entries.append(agg.to_yaml_block(args.queue_key))

        payload = {
            "generated_at_utc": iso(),
            "queue_key": args.queue_key,
            "queue_items_read": len(raw_items),
            "parse_errors": parse_errors,
            "aggregated_candidates": len(aggs),
            "new_entries": len(new_entries),
            "skipped_existing": skipped,
            "status_file": str(status_path),
            "dry_run": args.dry_run,
            "lock_file": args.lock_file,
        }

        if not args.dry_run and new_entries:
            updated = insert_backlog_entries(status_text, new_entries)
            # Safety check: ensure updated YAML still parses.
            yaml.safe_load(updated)
            status_path.write_text(updated, encoding="utf-8")

        # Trim queue after successful processing (or dry-run preview).
        if not args.dry_run:
            client.ltrim(args.queue_key, len(raw_items), -1)

        print("SKILL_BACKLOG_INGEST_RESULT")
        print(yaml.safe_dump(payload, sort_keys=False).strip())

        return 0


if __name__ == "__main__":
    raise SystemExit(main())
