#!/usr/bin/env python3
"""CLI entry point for trade history recap generation.

Supports manual trigger with test and dry-run flags.
Cron-friendly (exit 0 on success).

Usage:
    python scripts/run_trade_history_recap.py [--test] [--dry-run] [--date YYYY-MM-DD]

For ST-TRADING-001: Nightly Trade History Recap
"""

from __future__ import annotations

import argparse
import asyncio
import json
import logging
import sys
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

# Add project root to path
project_root = Path(__file__).parent.parent
sys.path.insert(0, str(project_root))

from src.reporting.trade_history_recap import (
    TradeHistoryRecap,
    run_nightly_recap,
)

# Try to import bootstrap, but don't fail if it's not available
try:
    from config.bootstrap import bootstrap  # noqa: E402
except ImportError:
    bootstrap = None

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s - %(name)s - %(levelname)s - %(message)s",
)
logger = logging.getLogger(__name__)


def parse_args() -> argparse.Namespace:
    """Parse command line arguments.

    Returns:
        Parsed arguments namespace
    """
    parser = argparse.ArgumentParser(
        description="Generate and send trade history recap reports to Discord #trading",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
    # Generate and send trade history recap for yesterday (normal operation)
    python scripts/run_trade_history_recap.py

    # Send test post immediately
    python scripts/run_trade_history_recap.py --test

    # Generate report without sending (dry run)
    python scripts/run_trade_history_recap.py --dry-run

    # Generate report for specific date
    python scripts/run_trade_history_recap.py --date 2024-01-15

    # Dry run for specific date
    python scripts/run_trade_history_recap.py --date 2024-01-15 --dry-run

Exit codes:
    0 - Success
    1 - Error (check logs)
    2 - Configuration error
        """,
    )

    parser.add_argument(
        "--test",
        action="store_true",
        help="Send a test post immediately to verify Discord connectivity",
    )

    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Generate report without sending to Discord",
    )

    parser.add_argument(
        "--date",
        type=str,
        metavar="YYYY-MM-DD",
        help="Generate report for specific date (default: yesterday)",
    )

    parser.add_argument(
        "--webhook-url",
        type=str,
        help="Override Discord webhook URL (default: from env var)",
    )

    parser.add_argument(
        "--channel-id",
        type=str,
        default="1444447985378398459",
        help="Discord channel ID (default: 1444447985378398459)",
    )

    parser.add_argument(
        "--json",
        action="store_true",
        help="Output result as JSON",
    )

    parser.add_argument(
        "--verbose",
        "-v",
        action="store_true",
        help="Enable verbose logging",
    )

    return parser.parse_args()


def parse_date(date_str: str) -> datetime:
    """Parse date string to datetime.

    Args:
        date_str: Date string in YYYY-MM-DD format

    Returns:
        Datetime object

    Raises:
        ValueError: If date format is invalid
    """
    try:
        return datetime.strptime(date_str, "%Y-%m-%d").replace(tzinfo=UTC)
    except ValueError as e:
        raise ValueError(
            f"Invalid date format: {date_str}. Use YYYY-MM-DD format."
        ) from e


async def run_test_post(recap: TradeHistoryRecap) -> dict[str, Any]:
    """Run a test post to verify Discord connectivity.

    Args:
        recap: TradeHistoryRecap instance

    Returns:
        Dictionary with result status
    """
    logger.info("Running test post to Discord #trading channel")

    # Create a test message
    test_content = """🧪 **Trade History Recap - Test Post**

This is a test message to verify the trade history recap integration is working correctly.

✓ Discord webhook configured
✓ Message formatting functional
✓ Channel connectivity verified

---
*Test generated by ChiseAI Trade History Recap System*"""

    # Check if webhook URL is configured
    if not recap.trading_webhook_url:
        error_msg = "No trading webhook URL configured. Set DISCORD_TRADING_WEBHOOK_URL or DISCORD_WEBHOOK_URL environment variable."
        logger.error(error_msg)
        print(f"✗ {error_msg}", file=sys.stderr)
        return {
            "success": False,
            "error": error_msg,
            "test": True,
        }

    result = await recap._send_to_discord(test_content)
    result["test"] = True

    if result["success"]:
        logger.info("✓ Test post sent successfully")
    else:
        logger.error(f"✗ Test post failed: {result.get('error')}")

    return result


async def main() -> int:
    """Main entry point.

    Returns:
        Exit code (0 on success, 1 on error, 2 on config error)
    """
    if bootstrap is not None:
        try:
            bootstrap(load_env=True)
        except Exception as e:
            logger.warning(f"Bootstrap failed (non-fatal): {e}")

    args = parse_args()

    if args.verbose:
        logging.getLogger().setLevel(logging.DEBUG)

    try:
        # Initialize recap generator
        recap = TradeHistoryRecap(
            trading_webhook_url=args.webhook_url,
            trading_channel_id=args.channel_id,
        )

        # Test mode - send test post
        if args.test:
            result = await run_test_post(recap)

            if args.json:
                print(json.dumps(result, indent=2, default=str))
            else:
                if result["success"]:
                    print("✓ Test post sent successfully")
                    if result.get("message_ids"):
                        print(f"  Message IDs: {', '.join(result['message_ids'])}")
                else:
                    print(f"✗ Test post failed: {result.get('error')}")

            await recap.close()
            return 0 if result["success"] else 1

        # Parse date if provided
        target_date = None
        if args.date:
            try:
                target_date = parse_date(args.date)
            except ValueError as e:
                logger.error(str(e))
                await recap.close()
                return 2

        # Log operation mode
        if args.dry_run:
            logger.info("Running in DRY RUN mode - report will not be sent")
        else:
            logger.info("Running in PRODUCTION mode - will send to #trading channel")

        # Generate and send recap
        result = await recap.generate_and_send_recap(
            date=target_date,
        )

        # Add dry_run flag to result if applicable
        if args.dry_run:
            result["dry_run"] = True

        # Output result
        if args.json:
            print(json.dumps(result, indent=2, default=str))
        else:
            if result["success"]:
                if result.get("message") == "No trades to report":
                    print("ℹ No trades found for the specified date")
                else:
                    print("✓ Trade history recap generated successfully")
                    if result.get("dry_run"):
                        print("  (Dry run - not sent)")
                    elif result.get("message_ids"):
                        print(f"  Message IDs: {', '.join(result['message_ids'])}")

                # Print summary
                trades_count = result.get("trades_count", 0)
                print(f"  Trades included: {trades_count}")
            else:
                error_msg = result.get("error", "Unknown error")
                print(f"✗ Failed: {error_msg}")
                # Log to stderr as well
                logger.error(f"Trade history recap failed: {error_msg}")

        await recap.close()
        return 0 if result["success"] else 1

    except Exception as e:
        logger.exception("Unexpected error")
        if args.json:
            print(json.dumps({"success": False, "error": str(e)}))
        else:
            print(f"✗ Error: {e}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    try:
        exit_code = asyncio.run(main())
        sys.exit(exit_code)
    except KeyboardInterrupt:
        logger.info("Interrupted by user")
        sys.exit(130)
    except Exception:
        logger.exception("Fatal error")
        sys.exit(1)
